### ISSUE TITLE
Signing pass with webServiceUrl using http throws an error

### ISSUE THREAD

**Issue by akoufatzis** [walletpass/pass-js#334]
Hello and thank you for the pass-js lib. I have a question. I finished setting up the webservice routes according to Apple documentation and I am able to sign and provide passes using your library. Unfortunately I am experiencing the following problem. When I define the webServiceUrl as "https://localhost:5000/wallet/" the signing of the pass works. I am then using the pass in the iOS Simulator where I have enabled Http in the developer options but I am still getting the "An SSL error has occurred and a secure connection to the server cannot be made" error. Trying to use **http** instead of **https** in the definition of the webServiceUrl in the pass.json produces a signing error. How can I test passes created and signed by this library locally?

**Comment by akoufatzis** [comment]
The issue is that the library does not allow signing passes that have a WebServiceUrl with **http** : https://github.com/walletpass/pass-js/blob/master/src/lib/base-pass.ts#L276 . I think adding an option to allow signing such passes for development purposes would be nice. I can create a PR for that if needed.

**Comment by tinovyatkin** [comment]
It's directly prohibited by documentation.

**Comment by akoufatzis** [comment]
Which documentation are you referring too? It is possible to sign passes that have a URL with http for the property webServiceUrl with Apple's official tool (signpass).

**Comment by tinovyatkin** [comment]
It's certainly possible to sign any JSON file with whatever content, the `throw` here is due to following requirement:

https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW1

_The web service must use the HTTPS protocol; the leading https:// is included in the value of this key._

However, it also says:
_On devices configured for development, there is UI in Settings to allow HTTP web services._
So, I will accept the PR if you up to it.

Thank you!

**Comment by akoufatzis** [comment]
I opened PR #338 for providing the ability to pass options to the library setting `allowHttp` flag to true for development purposes

**Comment by tinovyatkin** [comment]
@akoufatzis Thank you, released as part of 6.8 today.
